### ISSUE TITLE
希望作者著名设计蓝本为 Ocean

### ISSUE THREAD

**Issue by zhwangart** [Shen-Yu/hexo-theme-ayer#1]
主题 [Ocean](https://github.com/zhwangart/hexo-theme-ocean) 是开源的，但是希望作者在演绎之后著名设计蓝本来源于  [Ocean](https://github.com/zhwangart/hexo-theme-ocean)

![ocean](https://github.com/zhwangart/hexo-theme-ocean/raw/master/screenshots/hexo-theme-ocean.jpg)

**Comment by Shen-Yu** [comment]
> 主题 [Ocean](https://github.com/zhwangart/hexo-theme-ocean) 是开源的，但是希望作者在演绎之后著名设计蓝本来源于 [Ocean](https://github.com/zhwangart/hexo-theme-ocean)
> 
> ![ocean](https://github.com/zhwangart/hexo-theme-ocean/raw/master/screenshots/hexo-theme-ocean.jpg)



> 主题 [Ocean](https://github.com/zhwangart/hexo-theme-ocean) 是开源的，但是希望作者在演绎之后著名设计蓝本来源于 [Ocean](https://github.com/zhwangart/hexo-theme-ocean)
> 
> ![ocean](https://github.com/zhwangart/hexo-theme-ocean/raw/master/screenshots/hexo-theme-ocean.jpg)

你好，已经在Readme文件说明了，感谢~
