### ISSUE TITLE
请问如何修改文章显示的宽度？

### ISSUE THREAD

**Issue by guhailong18** [Shen-Yu/hexo-theme-ayer#10]
我在使用网页接入视频发现文章的宽度有些小。请问在哪里可以调整？还有就是如何添加密码验证，我在直接使用插件的时候，发现会导致文章无法打开，不知是要修改什么配置？望回答，十分感谢！

**Comment by Shen-Yu** [comment]
> 我在使用网页接入视频发现文章的宽度有些小。请问在哪里可以调整？还有就是如何添加密码验证，我在直接使用插件的时候，发现会导致文章无法打开，不知是要修改什么配置？望回答，十分感谢！

直接修改源码吧，/source/css/_partial/layout.styl 文件。 密码验证我这个主题是不支持的哦，请看相关插件的使用说明。
