### ISSUE TITLE
remixicon.min.css和pace.min.js的引用被ejs错误的渲染

### ISSUE THREAD

**Issue by acooler15** [Shen-Yu/hexo-theme-ayer#104]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/Shen-Yu/hexo-theme-ayer) version of hexo-theme-ayer.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [Ayer Issues](https://github.com/Shen-Yu/hexo-theme-ayer/issues), which does not help me.

---

## Expected behavior 
生成的静态页面中正确的引用“https:/cdn.jsdelivr.net/gh/Shen-Yu/cdn/css/remixicon.min.css”和“https:/cdn.jsdelivr.net/npm/pace-js@1.0.2/pace.min.js”
## Actual behavior 
![image](https://user-images.githubusercontent.com/19186382/105727874-7c33bb00-5f66-11eb-993f-817f0821d5a1.png)

- Links to demo site with this issue: https://www.lingyan8.com
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 

1. N/A
2. N/A
3. N/A

### Node.js and NPM Information

```
v14.15.4
6.14.10
```

### Package dependencies Information

```
hexo-site@0.0.0 /home/dev/blog
├── hexo@5.3.0
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-index@2.0.0
├── hexo-generator-searchdb@1.3.3
├── hexo-generator-tag@1.0.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-marked@3.3.0
├── hexo-renderer-stylus@2.0.1
├── hexo-server@2.0.0
└── hexo-theme-ayer@1.8.12
```

### HTML Configuration

```

```

### MiniValine Configuration

```

```

**Comment by Shen-Yu** [comment]
@acooler15 已修复~请更新一下
