### ISSUE TITLE
tags和categories页面是空的

### ISSUE THREAD

**Issue by small-ora** [Shen-Yu/hexo-theme-ayer#105]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/Shen-Yu/hexo-theme-ayer) version of hexo-theme-ayer.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [Ayer Issues](https://github.com/Shen-Yu/hexo-theme-ayer/issues), which does not help me.

---

## Expected behavior 
进入tags和categories页面有对应的标签和分类

## Actual behavior 
进入tags和categories页面没有对应的标签名称和分类名称展示,
但是在首页的博文都有正确的标签和分类,点击首页博文下面对应的分类可以进入到分类详情页面,可以看到属于这个分类的文章.

- Links to demo site with this issue: http://blog.zhaocheng.ltd/
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 

1. N/A
2. N/A
3. N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### HTML Configuration

```

```

### MiniValine Configuration

```

```

**Comment by Shen-Yu** [comment]
请参考： [说明文档](https://shen-yu.gitee.io/2019/ayer/#分类)

**Comment by small-ora** [comment]
> 请参考： [说明文档](https://shen-yu.gitee.io/2019/ayer/#%E5%88%86%E7%B1%BB)

好的,谢谢,看说明的不够仔细.
