### ISSUE TITLE
文章页标题目录遮挡文字/代码

### ISSUE THREAD

**Issue by hcxx** [Shen-Yu/hexo-theme-ayer#106]
## 我确认我已经查看了 

- [x] I am using [the latest](https://github.com/Shen-Yu/hexo-theme-ayer) version of hexo-theme-ayer.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [Ayer Issues](https://github.com/Shen-Yu/hexo-theme-ayer/issues), which does not help me.

---

## 预期行为 
 1. 目前文章页面向下滚动的时候(文章目录由固定变为浮动)，文章目录会向左边扩展一小部分，导致遮挡一个文字左右，还是会影响阅读的。如果可以：是否可以不向左边扩展，直接下滑跟随

## 实际行为 
 1. 文章目录由固定变为浮动，向左边扩展导致遮挡文字

**Comment by githubzjm** [comment]
遮挡表格+1

**Comment by Shen-Yu** [comment]
你好，这应该和分辨率有关

**Comment by hcxx** [comment]
> 你好，这应该和分辨率有关

您好，请问一下推荐的分辨率有哪些？无法保证每个人都能使用的推荐的分辨率。请问是否会进行优化。如果不打算进行优化，在等到您回复的推荐分辨率后，我会关闭这个issue。

**Comment by githubzjm** [comment]
> 你好，这应该和分辨率有关

当表格宽度比较长时就会发生侧目录半透明遮在表格上，可否规定目录显示的最大宽度，超出就加个水平滚动条？

**Comment by Shen-Yu** [comment]
@hcxx @githubzjm 你好，感谢反馈这个问题，跟据我的测试，正常的1920x1080都没有遮挡的问题，现在主流的屏幕分辨率也就是1080p以上了。这个问题其实当时我在写这个主题时已经做了考虑，所以把侧边目录做成浮动并设置了一定的透明度，个人觉得这对于低分辨率用户影响不大，遮挡只是暂时的，因为侧边目录会根据文章滚动而浮动。。如果这个问题反馈的用户较多，那我会考虑优化一下样式，谢谢。

**Comment by Shen-Yu** [comment]
@hcxx 你提的这个直接下滑跟随的建议我也考虑过，可能会把一部分目录直接遮挡了。

**Comment by hcxx** [comment]
> @hcxx @githubzjm 你好，感谢反馈这个问题，跟据我的测试，正常的1920x1080都没有遮挡的问题，现在主流的屏幕分辨率也就是1080p以上了。这个问题其实当时我在写这个主题时已经做了考虑，所以把侧边目录做成浮动并设置了一定的透明度，个人觉得这对于低分辨率用户影响不大，遮挡只是暂时的，因为侧边目录会根据文章滚动而浮动。。如果这个问题反馈的用户较多，那我会考虑优化一下样式，谢谢。
@Shen-Yu 感谢您的回答 。 @githubzjm 您的表格加水平滚动条的问题可以考虑新开一个issue，如果没有问题，我打算在明天关闭这个issue。

**Comment by githubzjm** [comment]
> > @hcxx @githubzjm 你好，感谢反馈这个问题，跟据我的测试，正常的1920x1080都没有遮挡的问题，现在主流的屏幕分辨率也就是1080p以上了。这个问题其实当时我在写这个主题时已经做了考虑，所以把侧边目录做成浮动并设置了一定的透明度，个人觉得这对于低分辨率用户影响不大，遮挡只是暂时的，因为侧边目录会根据文章滚动而浮动。。如果这个问题反馈的用户较多，那我会考虑优化一下样式，谢谢。
> 
> @Shen-Yu 感谢您的回答 。 @githubzjm 您的表格加水平滚动条的问题可以考虑新开一个issue，如果没有问题，我打算在明天关闭这个issue。

好的，谢谢大家的回答
