### ISSUE TITLE
latex公式只渲染了一部分

### ISSUE THREAD

**Issue by wwdok** [Shen-Yu/hexo-theme-ayer#108]
作者您好，不知道为什么我的个人网站突然404了，一开始好像是网络问题git push不了，然后按照网站的说法卸载了pandoc，后面发现我的文章没有渲染出markdown的语法，于是我又把pandoc装回去，装完之后我的网站就404了，作者能给点建议我怎么找出问题所在吗？我的仓库是：https://gitee.com/wwdok/wwdok

![image](https://user-images.githubusercontent.com/43233772/110244936-1fcbae80-7f9c-11eb-97b1-c0bf98aefe12.png)

**Comment by wwdok** [comment]
执行hexo g -d 时没有报错：
![image](https://user-images.githubusercontent.com/43233772/110246052-f06b7080-7fa0-11eb-85ba-37c5dcb7e623.png)

**Comment by Shen-Yu** [comment]
你好，首先排除是pandoc的问题，因为pandoc本身并不会对你搭建博客有任何影响，其次，从你的截图中也无法看出问题所在，但是从你仓库中可以看到有问题，正常push后所该有的文件应该是这样的：[我的博客](https://gitee.com/shen-yu/shen-yu)。

**Comment by wwdok** [comment]
看起来是没有生成index.html，这个问题算是hexo的问题吗，顺便问一下您有什么dubug思路吗

**Comment by Shen-Yu** [comment]
不好意思，这个不是hexo的问题，可能是你本地依赖没有正确安装。

**Comment by wwdok** [comment]
ayer的依赖吗，您觉得是哪个依赖呢，还是我重新全部安装一遍呢。是的话应该安装呢，还请大神指教！

**Comment by wwdok** [comment]
看来不止index.html没了，我的markdown博客也没了，也就是没有2020，2021这些文件夹

**Comment by wwdok** [comment]
**今天我重新新建了一个文件件，从hexo init 开始重新部署了一遍博客，这次就可以了。。。难道是node_modules的问题？我没验证。
但打开wwdok.github.io，我看到[有些文章](https://wwdok.github.io/2020/09/26/%E6%8D%9F%E5%A4%B1%E5%87%BD%E6%95%B0/)的数学公式没有完全渲染，像这样：**
![image](https://user-images.githubusercontent.com/43233772/111940998-0fbedd80-8b0b-11eb-9c12-921950eafb5b.png)

![image](https://user-images.githubusercontent.com/43233772/111940950-f0c04b80-8b0a-11eb-8f19-0b40d75d16a0.png)
**但在本地用typora预览markdown时，没有问题：**
![image](https://user-images.githubusercontent.com/43233772/111941068-32e98d00-8b0b-11eb-9c82-6c601c5cd82a.png)
![image](https://user-images.githubusercontent.com/43233772/111941137-5a405a00-8b0b-11eb-9f8f-c4042141db77.png)
**作者您觉得是什么问题呢，需要我发一下这些公式吗**

**Comment by wwdok** [comment]
后来按照教程《[让 Hexo 搭建的博客支持 LaTeX](https://cps.ninja/2019/03/16/hexo-with-latex/)》搞好了, 关键的步骤就四个：
```
## 0. 打开终端，进入 hexo 博客所在文件夹
，如果你随便在其他路径安装，可能接下来的步骤你等于没安装
$ cd my_hexo_blog

## 1. 安装 hexo ； --save 参数会让 npm 在安装 hexo-math 之后自动将它写入 package.json 文件里，以便之后多电脑同步时使用
$ npm install hexo-math --save

## 2. 卸载默认 markdown 渲染引擎 hexo-renderer-marked；若不卸载，会和新的引擎发生冲突
$ npm uninstall hexo-renderer-marked --save

## 3. 安装新引擎 hexo-renderer-kramed 
$ npm install hexo-renderer-kramed --save

## 4. 打开my_hexo_blog
/node_modules\kramed\lib\rules\inline.js
，修改escape和em：
var inline = {
  //escape: /^\\([\\`*{}\[\]()#$+\-.!_>])/,      // 注释掉的默认规则
  escape: /^\\([`*\[\]()#$+\-.!_>])/,            // 新增的规则
  autolink: /^<([^ >]+(@|:\/)[^ >]+)>/,
  url: noop,
  html: /^<!--[\s\S]*?-->|^<(\w+(?!:\/|[^\w\s@]*@)\b)*?(?:"[^"]*"|'[^']*'|[^'">])*?>([\s\S]*?)?<\/\1>|^<(\w+(?!:\/|[^\w\s@]*@)\b)(?:"[^"]*"|'[^']*'|[^'">])*?>/,
  link: /^!?\[(inside)\]\(href\)/,
  reflink: /^!?\[(inside)\]\s*\[([^\]]*)\]/,
  nolink: /^!?\[((?:\[[^\]]*\]|[^\[\]])*)\]/,
  reffn: /^!?\[\^(inside)\]/,
  strong: /^__([\s\S]+?)__(?!_)|^\*\*([\s\S]+?)\*\*(?!\*)/,
  //em: /^\b_((?:__|[\s\S])+?)_\b|^\*((?:\*\*|[\s\S])+?)\*(?!\*)/,    // 注释掉的默认规则
  em: /^\*((?:\*\*|[\s\S])+?)\*(?!\*)/,                               // 新增的规则
  code: /^(`+)\s*([\s\S]*?[^`])\s*\1(?!`)/,
  br: /^ {2,}\n(?!\s*$)/,
  del: noop,
  text: /^[\s\S]+?(?=[\\<!\[_*`$]| {2,}\n|$)/,
  math: /^\$\$\s*([\s\S]*?[^\$])\s*\$\$(?!\$)/,
};

//...
```
