### ISSUE TITLE
请问分类和标签的文章头的格式是什么？还有就是菜单是不能随意添加的吗？我加了几个后发现页面无法显示了，这是为什么？如何才能正确添加？

### ISSUE THREAD

**Issue by guhailong18** [Shen-Yu/hexo-theme-ayer#11]
我已在新建\source\_posts\categories和tags,配置也是根据你的说明配的，我使用了这样的文章头
tags: 娱乐
categories： 表情包
标签在主页面可以看得到，但是在点击标签出现的页面还是404

**Comment by Shen-Yu** [comment]
> 我已在新建\source_posts\categories和tags,配置也是根据你的说明配的，我使用了这样的文章头
> tags: 娱乐
> categories： 表情包
> 标签在主页面可以看得到，但是在点击标签出现的页面还是404

tags要数组的格式
