### ISSUE TITLE
自定义版权申明不支持超链接

### ISSUE THREAD

**Issue by hcxx** [Shen-Yu/hexo-theme-ayer#111]
该主题支持自定义版权申明，但是自定义的申明不支持md格式，
例如实现：本文遵守 [署名-非商业性使用-相同方式共享 4.0 国际 (CC BY-NC-SA 4.0)](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh-Hans)协议
实际结果是纯文本内容。

**Comment by Shen-Yu** [comment]
有空了再考虑优化，这个主要考虑到每个用户希望展示的协议都不一样，以及多语言支持。
