### ISSUE TITLE
加载页面时f12控制台有warning信息

### ISSUE THREAD

**Issue by q1393877285** [Shen-Yu/hexo-theme-ayer#112]
警示信息如下：
main.js:4 A parser-blocking, cross site (i.e. different eTLD+1) script, https://js.users.51.la/20544303.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.

我打开您的博客也有这个提示，问题定位应该是在source文件夹下的main.js中document.write('<script type="text/javascript"  src="https://js.users.51.la/20544303.js"><\/script>')所导致的，貌似异步加载不能用document.write方法？

**Comment by Shen-Yu** [comment]
你好，感谢提出的问题，这个warning只是我加的主题埋点代码在其他站点中cookie跨域导致的，不影响正常使用，忽略即可，目前已经弃用document.write方法。
