### ISSUE TITLE
后续会考虑增加文章投票、笔记、划线等功能吗？

### ISSUE THREAD

**Issue by wangwei1237** [Shen-Yu/hexo-theme-ayer#117]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/Shen-Yu/hexo-theme-ayer) version of hexo-theme-ayer.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [Ayer Issues](https://github.com/Shen-Yu/hexo-theme-ayer/issues), which does not help me.

---

## Expected behavior 
后续会考虑增加文章投票、笔记、划线等功能吗？这样被人在阅读文章的时候可以在线标注，记录笔记等。

## Actual behavior 

- Links to demo site with this feature: https://netflixtechblog.com/scaling-revenue-growth-tooling-87ff969d4241
- Links to repository or source code of the blog: https://netflixtechblog.com/scaling-revenue-growth-tooling-87ff969d4241

## Steps to reproduce the behavior

**Comment by Shen-Yu** [comment]
不会，考虑到博客加载速度，加上去显得过于臃肿

**Comment by wangwei1237** [comment]
> 不会，考虑到博客加载速度，加上去显得过于臃肿

确实会显得臃肿~
