### ISSUE TITLE
求助：代码块字体大小调整

### ISSUE THREAD

**Issue by andyppang** [Shen-Yu/hexo-theme-ayer#118]
## Issue Checklist 

- [x] I am using [the latest](https://github.com/Shen-Yu/hexo-theme-ayer) version of hexo-theme-ayer.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [Ayer Issues](https://github.com/Shen-Yu/hexo-theme-ayer/issues), which does not help me.

---

## Expected behavior 
我想调大代码块字体，可是我小白一枚，找半天也不知道修改哪个文件的哪个部分，请大佬明示需要怎样改，或者有空出个帮助文档吧，我看issue里面的4个关于字体修改的问题，都没有找到答案。致谢！

**Comment by Shen-Yu** [comment]
你好，主题样式用parcel进行打包，当然你也可以直接在外部引入样式。

**Comment by andyppang** [comment]
> 你好，主题样式用parcel进行打包，当然你也可以直接在外部引入样式。

抱歉，你说的我都不懂，我只会改改诸如"font-size: xx"的事，所以才想问 **修改哪个文件的哪个部分** ，如果不是这样子的，那我先放弃这个想法，先用着。谢谢

**Comment by Shen-Yu** [comment]
你好，如果你不熟悉打包，建议直接修改 `source/dist/` 目录下的 `main.css` 文件，代码块对应的选择器是 `.article-entry .highlight td`

**Comment by andyppang** [comment]
> 你好，如果你不熟悉打包，建议直接修改 `source/dist/` 目录下的 `main.css` 文件，代码块对应的选择器是 `.article-entry .highlight td`

感谢大佬指示这么详细，不然真找不到，问题解决了，我把 `.9em` 改成了 `1em`，自己看起来没那么费眼了。

再次感谢！！
