### ISSUE TITLE
Menu宽度自定义

### ISSUE THREAD

**Issue by AlexZhou1995** [Shen-Yu/hexo-theme-ayer#12]
Hi，这个主题超棒的！
但是我想如果Menu的宽度可以自定义就好了，模板里是“旅游”，“摄影”这种2个字的还好，如果是4个字的话，最后一个字会换行，有点不好看。

可以做到Menu宽度自定义吗？谢谢

**Comment by AlexZhou1995** [comment]
还有个小问题关于aboutme，我看md是写在_posts文件夹下面的，为什么我看你主页生成的aboutme页面在2019/about文件夹下面呀，我想生成个aboutme，目前还没成功TAT

**Comment by Shen-Yu** [comment]
> Hi，这个主题超棒的！
> 但是我想如果Menu的宽度可以自定义就好了，模板里是“旅游”，“摄影”这种2个字的还好，如果是4个字的话，最后一个字会换行，有点不好看。
> 
> 可以做到Menu宽度自定义吗？谢谢

你好，感谢提出的建议，主题最新已经支持单行最大宽度4个文字，请用命令行`git pull`更新主题，如果还是觉得不够，你可以在主题目录的`source/css/_variables.styl`文件里面找到有个`aside-width`属性，可以自行调整数字大小以调整Menu宽度。
