### ISSUE TITLE
手机下，float_btns的div随着页面的滑动而划出了当前窗口 

### ISSUE THREAD

**Issue by wangwei1237** [Shen-Yu/hexo-theme-ayer#121]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/Shen-Yu/hexo-theme-ayer) version of hexo-theme-ayer.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [Ayer Issues](https://github.com/Shen-Yu/hexo-theme-ayer/issues), which does not help me.

---

## 手机下，float_btns的div随着页面的滑动而划出了当前窗口 
![image](https://user-images.githubusercontent.com/3480154/118268400-ef4e4680-b4ef-11eb-8055-a9ba732bbd94.png)

**Comment by Shen-Yu** [comment]
@wangwei1237 谢谢，已经修复~ https://github.com/Shen-Yu/hexo-theme-ayer/commit/302c6080fd78cf1a0e08366014b8d11b97dba846
