### ISSUE TITLE
Site can't be viewed as expected on ipad

### ISSUE THREAD

**Issue by d1gg12** [Shen-Yu/hexo-theme-ayer#127]
## Issue Checklist 

- [x] I am using [the latest](https://github.com/Shen-Yu/hexo-theme-ayer) version of hexo-theme-ayer.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [Ayer Issues](https://github.com/Shen-Yu/hexo-theme-ayer/issues), which does not help me.

---

## Expected behavior 

Looks like it does on PC.

## Actual behavior 

![image](https://user-images.githubusercontent.com/51625608/122340847-5f2f7100-cf75-11eb-804e-7c9d44a31ea0.png)

- Links to demo site with this issue: https://shen-yu.gitee.io/
- 
## Steps to reproduce the behavior 

1. View the demo site with ipad

**Comment by Shen-Yu** [comment]
Thanks, I have not tested it on ipad, as far as i know, it can also be normally showed on ipad, just like on iphone, can you tell me which component is not displaying properly?
