### ISSUE TITLE
插入图片之后没有显示图注

### ISSUE THREAD

**Issue by wangqian0306** [Shen-Yu/hexo-theme-ayer#128]
## Issue Checklist 

- [x] I am using [the latest](https://github.com/Shen-Yu/hexo-theme-ayer) version of hexo-theme-ayer.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [Ayer Issues](https://github.com/Shen-Yu/hexo-theme-ayer/issues), which does not help me.

---

## Expected behavior 

在博文中采用如下方式添加图片

```text
![图注](<路径>)
```

可以在页面上同时看到图片和图注文本

## Actual behavior 

没有正常显示图注，渲染结果如下：

```html
<img src="https://..." alt="图注">
```

而原生主题的渲染方式如下：

```html
<p>
    <a href="https://..." data-fancybox="gallery" data-caption="图注">
        <img src="https://..." alt="图注">
    </a>
    <span class="caption">图注</span>
</p>
```

## Steps to reproduce the behavior 

1. 切换回 Hexo 默认主题
2. 使用 `hexo server` 命令运行博客
3. 检查页面

**Comment by wangqian0306** [comment]
@Shen-Yu 作者大大你好，这个是我的配置有问题吗？还是说会在后续版本进行完善呢？

**Comment by Shen-Yu** [comment]
没听懂你的意思，alt不就是图注吗
