### ISSUE TITLE
目录满了时展示不全

### ISSUE THREAD

**Issue by dbses** [Shen-Yu/hexo-theme-ayer#129]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/Shen-Yu/hexo-theme-ayer) version of hexo-theme-ayer.
- [x] #130

---

## Actual behavior 

- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 

1. 新建一篇文章；
2. 将右侧目录填满，比如写50个1级目录；
3. 可看到效果：目录展示不全，也不会滑动；

如下图：

![](https://gitee.com/yanglu_u/ImgRepository/raw/master/20210625023839.png)

### Node.js and NPM Information

```
v14.15.0
6.14.8
```

### Package dependencies Information

```
+-- hexo@5.4.0
+-- hexo-admin@2.3.0
+-- hexo-deployer-git@3.0.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-feed@3.0.0
+-- hexo-generator-index-pin-top@0.2.2
+-- hexo-generator-searchdb@1.3.4
+-- hexo-generator-tag@1.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@4.0.0
+-- hexo-renderer-stylus@2.0.1
+-- hexo-server@2.0.0
`-- hexo-theme-landscape@0.0.3
```

### HTML Configuration

```

```

### MiniValine Configuration

```

```

**Comment by Shen-Yu** [comment]
Fixed: https://github.com/Shen-Yu/hexo-theme-ayer/commit/72c4fd9761e0022e4f6b7ea23ca0c17b4d9f3440
