### ISSUE TITLE
关于图注问题的补充说明

### ISSUE THREAD

**Issue by wangqian0306** [Shen-Yu/hexo-theme-ayer#131]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/Shen-Yu/hexo-theme-ayer) version of hexo-theme-ayer.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [Ayer Issues](https://github.com/Shen-Yu/hexo-theme-ayer/issues), which does not help me.

---

## Expected behavior 

在博文中采用如下方式添加图片

```text
![图注](<路径>)
```

可以在页面上同时看到图片和图注文本

## Actual behavior 

没有正常显示图注，渲染结果如下：

```html
<img src="https://..." alt="图注">
```

![image](https://user-images.githubusercontent.com/38555288/123897640-55a30180-d996-11eb-925c-4793232845e2.png)

而原生主题的渲染方式如下：

```html
<p>
    <a href="https://..." data-fancybox="gallery" data-caption="图注">
        <img src="https://..." alt="图注">
    </a>
    <span class="caption">图注</span>
</p>
```

![image](https://user-images.githubusercontent.com/38555288/123897531-1bd1fb00-d996-11eb-9250-31caac7d4b75.png)

## Steps to reproduce the behavior 

1. 切换回 Hexo 默认主题
2. 使用 hexo server 命令运行博客
3. 检查页面

## 额外描述

在两个主题中的图注在点击图片之后的浏览页面都能正常显示，但是在默认情况下 ayer 主题确实把图注吞掉了。

## 关于 `<img>` 标签中 alt 属性的说明

因为 alt 属性确实没有显示在页面上所以我去查了下它的作用：

<html>
<body>

属性 | 值 | 描述
-- | -- | --
alt | text | 规定图像的替代文本。

</body>
</html>

[参考链接](https://www.w3school.com.cn/tags/tag_img.asp)

**Comment by wangqian0306** [comment]
@Shen-Yu 作者大大，这样写清楚吗？之前我写过 ISSUE 的在 #128

**Comment by Shen-Yu** [comment]
@wangqian0306 嗯嗯，知道你的意思了，初步判定这应该是和hexo官方的markdown渲染器不一致所导致，等有空我研究一下。。

**Comment by Shen-Yu** [comment]
额，不是渲染器的问题，加了一段代码，已经实现图注功能:  https://github.com/Shen-Yu/hexo-theme-ayer/commit/3d4a4fcc7eb4e5107090f20ccbd6ded9a7a1ab60

**Comment by bianyukun1213** [comment]
在 `![替代文本](图片地址 "标题")` 这种形式下，优先使用 `""` 内的标题（ `title` 属性）比较好。替代文本（`alt` 属性）描述的是图像的内容，在图像无法加载时显示，也被读屏软件用于朗读。替代文本与标题并不一定相同，因为标题并不一定是对图像内容的直观描述。

对于图注，我建议这样处理：  
如果 Markdown 语句内指定了图片的标题，那么就显示标题，否则显示替代文本。因为很多人，包括之前的我，都是误把替代文本当作标题使用的，但其实它俩是不同的概念。这样处理的话就具备了一定的兼容性，即使替代文本被误当作标题使用，也会显示出来。

拿之前的图片举个例子：

`![一幅复杂的流程图](图片地址 "Kafka 消息发送")`

- 图注显示标题：

  盲人用户通过读屏软件”看到“的是”一幅复杂的流程图“，于是对图片的内容有了直观的印象，但对于我们，这显而易见，不需要说明，下方的图注让我们（以及盲人用户）知道这幅图被称作”Kafka 消息发送“。另外，如果把鼠标指针放到图片上的话，也会显示出悬浮文本”Kafka 消息发送“。

- 图注显示替代文本：

  盲人用户”看到“两次”Kafka 消息发送“，但他或她不会知道”Kafka 消息发送“这张图究竟长什么样子，因此相对于我们少了解到许多信息。
