### ISSUE TITLE
关于数学公式渲染的一些bug

### ISSUE THREAD

**Issue by yifeianyi** [Shen-Yu/hexo-theme-ayer#132]
问题blog链接：https://lzyblog.site/2020/11/05/Solution/NiuKe/%E7%89%9B%E5%AE%A2%20%E6%95%B0%E5%AD%A6%E8%80%83%E8%AF%95/

 最近返现，主题渲染数学公式上出现了一些问题，如分段函数无法解析，部分加粗不知道

为何没有实现等，但这些在本地typora上都是正常的。

**Comment by yifeianyi** [comment]
bug位置渲染对比图：![image-20210701234748225](https://photos-1302100213.cos.ap-guangzhou.myqcloud.com/imgs/Blog/image-20210701234748225.png)

**Comment by Shen-Yu** [comment]
你好，根据你博客上显示的是，katex已经启用，mathjax未启用，另外请仔细检查公式是否书写正确。

**Comment by yifeianyi** [comment]
嗷，不好意思，链接发错了，应该是这个https://lzyblog.site/2020/11/04/Solution/NiuKe/%E7%89%9B%E5%AE%A2%20%E5%86%8D%E7%BC%96%E5%8F%B7/

**Comment by yifeianyi** [comment]
> 你好，根据你博客上显示的是，katex已经启用，mathjax未启用，另外请仔细检查公式是否书写正确。
嗷，不好意思，链接发错了，应该是这个https://lzyblog.site/2020/11/04/Solution/NiuKe/%E7%89%9B%E5%AE%A2%20%E5%86%8D%E7%BC%96%E5%8F%B7/
