### ISSUE TITLE
侧边栏

### ISSUE THREAD

**Issue by MOOnLyer** [Shen-Yu/hexo-theme-ayer#133]
## Issue Checklist 

- [x] I am using [the latest](https://github.com/Shen-Yu/hexo-theme-ayer) version of hexo-theme-ayer.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [Ayer Issues](https://github.com/Shen-Yu/hexo-theme-ayer/issues), which does not help me.

---

## Expected behavior 

电脑版以及手机版侧边栏都是默认隐藏

## Actual behavior 

电脑版侧边栏默认隐藏 但是手机版默认显示

## Steps to reproduce the behavior 

layout下的layout.ejs做如下更改
```diff
- <main class="content on">
+ <main class="content">

- <aside class="sidebar on">
+ <aside class="sidebar">
```
## Other Information 

修改前应该为 电脑版侧边栏默认显示 手机版默认隐藏
怀疑是手机版相关代码影响
但是没找到在哪
还望指教 达到电脑版以及手机版侧边栏都是默认隐藏的目的

**Comment by Shen-Yu** [comment]
你好，主题本身设计的侧边栏就是PC端显示，手机端隐藏，如果希望自定义，请自行修改。

**Comment by MOOnLyer** [comment]
我尝试修改了layout下的layout.ejs 如文中所示
但结果 变成 PC端隐藏 手机端显示了
所以还望指点一二 谢谢

**Comment by MOOnLyer** [comment]
> 你好，主题本身设计的侧边栏就是PC端显示，手机端隐藏，如果希望自定义，请自行修改。

我尝试修改了layout下的layout.ejs 如文中所示
但结果 变成 PC端隐藏 手机端显示了
所以还望指点一二 谢谢
