### ISSUE TITLE
Firefox 90.0.2 下博客页面底部有大量空白

### ISSUE THREAD

**Issue by bianyukun1213** [Shen-Yu/hexo-theme-ayer#134]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/Shen-Yu/hexo-theme-ayer) version of hexo-theme-ayer.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [Ayer Issues](https://github.com/Shen-Yu/hexo-theme-ayer/issues), which does not help me.

---

## Expected behavior 

博客页面底部正常显示。

## Actual behavior 

博客页面底部有大量空白。

![](https://z3.ax1x.com/2021/07/27/W4mHj1.png)

- Links to demo site with this issue: [https://shen-yu.gitee.io/](https://shen-yu.gitee.io/)
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 

1. 用 Firefox 90.0.2 打开 [https://shen-yu.gitee.io/](https://shen-yu.gitee.io/)。

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### HTML Configuration

```

```

### MiniValine Configuration

```

```

**Comment by Shen-Yu** [comment]
你好，感谢你的反馈，我本地用win10系统下的firefox90.0.2版本并没有出现你截图的样式问题，是否可以告知你的系统？另外你用chrome打开也会出现这个问题吗？

**Comment by bianyukun1213** [comment]
> 
> 
> 你好，感谢你的反馈，我本地用win10系统下的firefox90.0.2版本并没有出现你截图的样式问题，是否可以告知你的系统？另外麻烦你用chrome测试一下也会出现这个问题吗？如果是的话，请截图全一点给我，我会进行排查
> 
> ![image](https://user-images.githubusercontent.com/13065982/127099304-bccb60df-6d5e-49eb-a9b5-e7da63fed82e.png)

```
版本	Windows 10 专业工作站版
版本号	20H2
安装日期	‎2020/‎5/‎29
操作系统内部版本	19042.1110
体验	Windows Feature Experience Pack 120.2212.3530.0
```
已经关闭了所有的浏览器扩展，还是有这个问题。这个问题在”主页“出现，归档页面是没有问题的。Chrome 没装，但是用同样基于 Chromium 的新版 Microsoft Edge 测试是正常显示的。

**Comment by Shen-Yu** [comment]
已经修复~ a9db32d0cb2c7ce560472a24
