### ISSUE TITLE
建议图注优先使用 Markdown 语句中的标题，而非替代文本

### ISSUE THREAD

**Issue by bianyukun1213** [Shen-Yu/hexo-theme-ayer#135]
在 `![替代文本](图片地址 "标题")` 这种形式下，优先使用 `""` 内的标题（ `title` 属性）比较好。替代文本（`alt` 属性）描述的是图像的内容，在图像无法加载时显示，也被读屏软件用于朗读。替代文本与标题并不一定相同，因为标题并不一定是对图像内容的直观描述。

对于图注，我建议这样处理：  
如果 Markdown 语句内指定了图片的标题，那么就显示标题，否则显示替代文本。因为很多人，包括之前的我，都是误把替代文本当作标题使用的，但其实它俩是不同的概念。这样处理的话就具备了一定的兼容性，即使替代文本被误当作标题使用，也会显示出来。

拿之前的图片举个例子：

`![一幅复杂的流程图](图片地址 "Kafka 消息发送")`

- 图注显示标题：

  盲人用户通过读屏软件”看到“的是”一幅复杂的流程图“，于是对图片的内容有了直观的印象，但对于我们，这显而易见，不需要说明，下方的图注让我们（以及盲人用户）知道这幅图被称作”Kafka 消息发送“。另外，如果把鼠标指针放到图片上的话，也会显示出悬浮文本”Kafka 消息发送“。

- 图注显示替代文本：

  盲人用户”看到“两次”Kafka 消息发送“，但他或她不会知道”Kafka 消息发送“这张图究竟长什么样子，因此相对于我们少了解到许多信息。

_Originally posted by @bianyukun1213 in https://github.com/Shen-Yu/hexo-theme-ayer/issues/131#issuecomment-887244821_

**Comment by Shen-Yu** [comment]
这样实现起来太麻烦了，而且markdown渲染引擎就是默认这样的。
