### ISSUE TITLE
1.9.3版本首页的侧边栏按钮和上滑到顶部以及黑夜模式都失效了

### ISSUE THREAD

**Issue by wangwei1237** [Shen-Yu/hexo-theme-ayer#136]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [ ] I am using [the latest](https://github.com/Shen-Yu/hexo-theme-ayer) version of hexo-theme-ayer.
- [ ] I have reviewed the latest Roadmap on GitHub and searched for current [Ayer Issues](https://github.com/Shen-Yu/hexo-theme-ayer/issues), which does not help me.

---

## Actual behavior 

- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 

1. N/A
2. N/A
3. N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### HTML Configuration

```

```

### MiniValine Configuration

```

```

**Comment by Shen-Yu** [comment]
@wangwei1237 这应该是jquery版本升级导致的，我这边本地测试是好的，可能是你本地还没完全更新，请重新拉一下主题代码。

**Comment by wangwei1237** [comment]
> @wangwei1237 这应该是jquery版本升级导致的，我这边本地测试是好的，可能是你本地还没完全更新，请重新拉一下主题代码。

确实是这个问题，重新拉取代码更新之后正常了。感谢~
