### ISSUE TITLE
每篇文章最后都有个黑框，求指点下

### ISSUE THREAD

**Issue by GOGOYAO** [Shen-Yu/hexo-theme-ayer#137]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [ ] I am using [the latest](https://github.com/Shen-Yu/hexo-theme-ayer) version of hexo-theme-ayer.
- [ ] I have reviewed the latest Roadmap on GitHub and searched for current [Ayer Issues](https://github.com/Shen-Yu/hexo-theme-ayer/issues), which does not help me.

---

## Expected behavior 
文章正常显示
## Actual behavior 

每篇文章的最后有个黑框。
![image](https://user-images.githubusercontent.com/18675094/127770878-ab8336e0-ba28-4381-aa46-7077219cb364.png)

- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

https://gogoyao.github.io/2021/08/01/about/

## Steps to reproduce the behavior 

1. N/A
2. N/A
3. N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### HTML Configuration

```

```

### Ayer Configuration

```

```

**Comment by Shen-Yu** [comment]
你好，这应该是你评论还没配置成功的原因。
