### ISSUE TITLE
如何修改字体及颜色

### ISSUE THREAD

**Issue by longqianh** [Shen-Yu/hexo-theme-ayer#14]
请问一下在哪里修改title、subtitle、archives-artitle-title的字体、颜色？感谢！！
另外，请问可以实现这样的需求吗：archive-article的title原本是黑色或者灰色，鼠标移动到上面title会变成蓝色，而不是一直是蓝色

**Comment by Shen-Yu** [comment]
> 请问一下在哪里修改title、subtitle、archives-artitle-title的字体、颜色？感谢！！
> 另外，请问可以实现这样的需求吗：archive-article的title原本是黑色或者灰色，鼠标移动到上面title会变成蓝色，而不是一直是蓝色

自己修改源码吧
