### ISSUE TITLE
如何实现首页的照片滚动？

### ISSUE THREAD

**Issue by DF-Master** [shen-yu/hexo-theme-ayer#141]
作者你好，非常喜欢你的这个主题。
我希望能实现首页照片滚动切换的功能，一时不知从何下手，您是否能给予意见或建议？

**Comment by shen-yu** [comment]
你好，可自行引入swiper库

**Comment by DF-Master** [comment]
似乎不行，我希望能实现置顶的大照片的滚动，但没有在swiper中找到这样的功能？
