### ISSUE TITLE
如何自动生成Categories的标题

### ISSUE THREAD

**Issue by adminerest** [Shen-Yu/hexo-theme-ayer#15]
你好，想问一下categories底下各个分类的标题怎么自动生成，我显示是undefined，您的展示页面上也是undefined，想问一下如何解决，谢谢！
[问题页面](https://shen-yu.gitee.io/categories/技术/)

**Comment by Shen-Yu** [comment]
> 你好，想问一下categories底下各个分类的标题怎么自动生成，我显示是undefined，您的展示页面上也是undefined，想问一下如何解决，谢谢！
> [问题页面](https://shen-yu.gitee.io/categories/%E6%8A%80%E6%9C%AF/)

请看说明文档：
![image](https://user-images.githubusercontent.com/13065982/73602021-47856180-45a7-11ea-9b2c-33f15a73f8ff.png)

我的是好的呢：
![image](https://user-images.githubusercontent.com/13065982/73602031-6a177a80-45a7-11ea-8d04-599faade0d35.png)

**Comment by adminerest** [comment]
<img width="639" alt="82F927D2-B29C-4204-B588-8E82FA404777" src="https://user-images.githubusercontent.com/43260539/73602075-60dadd80-45a8-11ea-8b96-adbdb5a1e0de.png">
我的意思是categories下面各个分类的页面title，我这边和您的页面全部都是undefined，不知道如何解决

**Comment by Shen-Yu** [comment]
> <img alt="82F927D2-B29C-4204-B588-8E82FA404777" width="639" src="https://user-images.githubusercontent.com/43260539/73602075-60dadd80-45a8-11ea-8b96-adbdb5a1e0de.png">
> 
> 我的意思是categories下面各个分类的页面title，我这边和您的页面全部都是undefined，不知道如何解决

恩恩，感谢提出的问题，我已经修复了~你再git pull更新下试试

**Comment by Shen-Yu** [comment]
![image](https://user-images.githubusercontent.com/13065982/73602255-b82e7d00-45ab-11ea-9071-db4cc30ddcd5.png)

**Comment by adminerest** [comment]
可以了，非常感谢！
