### ISSUE TITLE
node warnings 

### ISSUE THREAD

**Issue by Bennett561** [shen-yu/hexo-theme-ayer#154]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/Shen-Yu/hexo-theme-ayer) version of hexo-theme-ayer.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [Ayer Issues](https://github.com/Shen-Yu/hexo-theme-ayer/issues), which does not help me.

---

## Expected behavior 
正常运行

## Actual behavior 
运行没有大问题，在本地服务器跑的时候，可以看到Node报错
```
(node:30441) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:30441) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:30441) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
(node:30441) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(node:30441) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:30441) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
```

- Links to demo site with this issue: [mysite](https://bennett561.gitee.io/)
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 

1. hexo s

### Node.js and NPM Information

```
(tf_m1) ➜  blog node -v
v17.9.0
(tf_m1) ➜  blog npm -v
8.5.5
```

### Package dependencies Information

```
hexo-site@0.0.0 /Users/ben/Documents/blog
├── hexo-deployer-git@3.0.0
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-index@2.0.0
├── hexo-generator-searchdb@1.4.0
├── hexo-generator-tag@1.0.0
├── hexo-renderer-ejs@2.0.0
├── hexo-renderer-kramed@0.1.4
├── hexo-renderer-mathjax@0.6.0
├── hexo-renderer-stylus@2.0.1
├── hexo-server@3.0.0
├── hexo-theme-landscape@0.0.3
└── hexo@6.1.0
```

**Comment by shen-yu** [comment]
你好，感谢你提出的这个问题，但这无法在我本地复现，我猜测这是由于node版本所导致的。

**Comment by ben-xj** [comment]
> 

好的，谢谢啦
