### ISSUE TITLE
侧边栏中的主题分类无法减少

### ISSUE THREAD

**Issue by wangqian0306** [shen-yu/hexo-theme-ayer#158]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/Shen-Yu/hexo-theme-ayer) version of hexo-theme-ayer.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [Ayer Issues](https://github.com/Shen-Yu/hexo-theme-ayer/issues), which does not help me.

---

## Expected behavior 

依据配置文件显示对应主题：

```markdown
menu:
  主页: /
  归档: /archives
  分类: /categories
  标签: /tags
  关于我: /2020/about
  测试: /test
```

## Actual behavior 

显示了如下主题：

![image](https://user-images.githubusercontent.com/38555288/173297066-f5268930-afa1-43e1-b466-68c63b141560.png)

默认的主题被重新添加了回来，无法被删去

### Package dependencies Information

经过测试 ：

`1.9.7-0` 版本和 `1.9.6` 版本都有这样的问题

**Comment by Out-Of-Rain** [comment]
同问，有解决方案吗？

**Comment by Gainlos** [comment]
@wangqian0306  @Out-Of-Rain  对于这个问题我找到了解决方案，你不仅要在源文件的_config.ayer.yml更改menu,你还需要在theme-hexo的_config.yml中删去你不需要的menu子项，推测是整体的config是取前者和后者的并集，冲突处以前者为准，希望能帮助到你们

**Comment by wangqian0306** [comment]
好的，非常感谢。@Gainlos
