### ISSUE TITLE
分享功能能增加其他的社交分享功能吗？比如微信，头条等。

### ISSUE THREAD

**Issue by wangwei1237** [Shen-Yu/hexo-theme-ayer#16]
目前看，分享只能分享到推特，facebook等国外的社交平台，什么时间能支持国内的社交平台的分享呢？比如微信，QQ，头条等。

**Comment by Shen-Yu** [comment]
> 目前看，分享只能分享到推特，facebook等国外的社交平台，什么时间能支持国内的社交平台的分享呢？比如微信，QQ，头条等。

你好，已经增加~

**Comment by wangwei1237** [comment]
已在自己的站点上更新，太赞了。
