### ISSUE TITLE
package.json 缺少 stylus 依赖

### ISSUE THREAD

**Issue by phygerr** [shen-yu/hexo-theme-ayer#160]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [ ] I am using [the latest](https://github.com/Shen-Yu/hexo-theme-ayer) version of hexo-theme-ayer.
- [ ] I have reviewed the latest Roadmap on GitHub and searched for current [Ayer Issues](https://github.com/Shen-Yu/hexo-theme-ayer/issues), which does not help me.

---

## Actual behavior 

- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 

1. N/A
2. N/A
3. N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### HTML Configuration

```

```

### MiniValine Configuration

```

```

**Comment by thihazawsatellite** [comment]
thank

**Comment by phygerr** [comment]
我用vercel直接部署本仓库，Output Directory总是不对，public和source/dist均不对，正确的应该是什么呢？
