### ISSUE TITLE
请教搜索功能和主页显示内容的问题

### ISSUE THREAD

**Issue by AloneAlive** [Shen-Yu/hexo-theme-ayer#17]
hi，非常感谢您的主题，非常棒！
我的网站：  http://wizzie.top/
请教几个问题，
1. 我的网站按照你的方法装了插件，但是搜索功能没有用，在public也有生成search.xml和search文件夹。这是为什么？
2. 我的文章比较多，发现只能使用一个一个添加来限制主页显示的字数，是否可以添加一个显示数字的控制？
3. 请教文章的宽度怎么修改源码？

**Comment by Shen-Yu** [comment]
> hi，非常感谢您的主题，非常棒！
> 我的网站： http://wizzie.top/
> 请教几个问题，
> 
> 1. 我的网站按照你的方法装了插件，但是搜索功能没有用，在public也有生成search.xml和search文件夹。这是为什么？
> 2. 我的文章比较多，发现只能使用一个一个添加来限制主页显示的字数，是否可以添加一个显示数字的控制？
> 3. 请教文章的宽度怎么修改源码？

1. 请先尝试`hexo clean`清掉缓存，然后重新生成，参考文档[hexo-generator-searchdb](https://github.com/theme-next/hexo-generator-searchdb)
2. 已经添加这个功能，请先`git pull`更新主题，在_config.yml文件中把`excerpt_all`设置成`true`
3. 修改文章宽度请自行在/source/css/_variables.styl中修改`wrap-width`变量
