### ISSUE TITLE
http请求被blocke导致按键元素、数学公式无法正常显示

### ISSUE THREAD

**Issue by hydrogenhy** [shen-yu/hexo-theme-ayer#176]
近期突然数学公式、按钮等无法生效，F12后查看报错为：
Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure script 'http://cdn.staticfile.net/pace/1.2.4/pace.min.js'. This request has been blocked; the content must be served over HTTPS.

**Comment by Francklin** [comment]
推荐使用webcache.cn替代，staticfile 已被投毒
