### ISSUE TITLE
Ayer表格问题

### ISSUE THREAD

**Issue by rausen** [Shen-Yu/hexo-theme-ayer#18]
作者大大您好：
虽然您设置了表格格式，但是在generate的时候会出现无法渲染的问题
我查询了一下，修改了`ayer/source/css/_extend.styl`的table部分的代码如下：
```stylus
  table
    width 100%
    max-width 65em
    border 1px solid #dedede
    margin 15px auto
    border-collapse collapse
    empty-cells show
    th,td
        height 35px
        border 1px solid #dedede
        padding 0 10px
    th
        font-weight bold
        text-align center !important
        background rgba(158, 188, 226, .2)
        white-space nowrap
    tbody tr:nth-child(2n)
        background rgba(158, 188, 226, .12)
    td:nth-child(1)
        white-space nowrap
    tbody tr:hover
        background #efefef
```
就比较好看了，希望您能merge到代码中，谢谢~

**Comment by Shen-Yu** [comment]
> 作者大大您好：
> 虽然您设置了表格格式，但是在generate的时候会出现无法渲染的问题
> 我查询了一下，修改了`ayer/source/css/_extend.styl`的table部分的代码如下：
> 
> ```stylus
>   table
>     width 100%
>     max-width 65em
>     border 1px solid #dedede
>     margin 15px auto
>     border-collapse collapse
>     empty-cells show
>     th,td
>         height 35px
>         border 1px solid #dedede
>         padding 0 10px
>     th
>         font-weight bold
>         text-align center !important
>         background rgba(158, 188, 226, .2)
>         white-space nowrap
>     tbody tr:nth-child(2n)
>         background rgba(158, 188, 226, .12)
>     td:nth-child(1)
>         white-space nowrap
>     tbody tr:hover
>         background #efefef
> ```
> 
> 就比较好看了，希望您能merge到代码中，谢谢~

好的，谢谢，我改一下
