### ISSUE TITLE
如何把css和js通过CDN加速

### ISSUE THREAD

**Issue by gaficat** [Shen-Yu/hexo-theme-ayer#21]
想给自己的博客套一个CDN全站加速，自己控制css和js样式的缓存刷新太麻烦了。

所以问一下，把主题相关的CSS，js文件统一放到又拍或者七牛云的文件存储上去，访问的之后直接通过CDN访问样式，加速博客，应该如何修改？

**Comment by Shen-Yu** [comment]
> 想给自己的博客套一个CDN全站加速，自己控制css和js样式的缓存刷新太麻烦了。
> 
> 所以问一下，把主题相关的CSS，js文件统一放到又拍或者七牛云的文件存储上去，访问的之后直接通过CDN访问样式，加速博客，应该如何修改？

你好，主题里的静态资源已经用了jsdelivr来实现全球加速，无需放到其他CDN上去

**Comment by gaficat** [comment]
能否替换成自己的？

**Comment by Shen-Yu** [comment]
> 能否替换成自己的？

可以换成自己的，但需要你手动把链接地址替换掉
