### ISSUE TITLE
怎么禁用封面图上的标题

### ISSUE THREAD

**Issue by peguine** [Shen-Yu/hexo-theme-ayer#23]
![image](https://user-images.githubusercontent.com/56867901/75144828-c5660400-5732-11ea-97e3-92de9eda230a.png)

请问怎么设置可以不显示这个标题，我的网站标题比较长。在文档里没看到这个设置项。谢谢

**Comment by Shen-Yu** [comment]
> ![image](https://user-images.githubusercontent.com/56867901/75144828-c5660400-5732-11ea-97e3-92de9eda230a.png)
> 
> 请问怎么设置可以不显示这个标题，我的网站标题比较长。在文档里没看到这个设置项。谢谢

博客下面的config.yml里的title属性不填，就不会显示
