### ISSUE TITLE
关于网易云音乐无法自动播放

### ISSUE THREAD

**Issue by hahahaozi** [Shen-Yu/hexo-theme-ayer#26]
我设定了音乐ID，页面上可以显示歌曲名称，但无法自动播放，点击播放按钮依然无效。

**Comment by Shen-Yu** [comment]
> 我设定了音乐ID，页面上可以显示歌曲名称，但无法自动播放，点击播放按钮依然无效。

你好，可能是你选的音乐有版权限制

**Comment by hahahaozi** [comment]
谢谢，已发现问题为歌曲版权不允许外部链接。
