### ISSUE TITLE
搜索功能无法正常使用

### ISSUE THREAD

**Issue by lNeverl** [Shen-Yu/hexo-theme-ayer#27]
部署到github之后搜索功能无法正常使用。

**Comment by Shen-Yu** [comment]
> 部署到github之后搜索功能无法正常使用。

你好，请检查根目录下是否有`search.xml`文件，另外你需要`hexo clean`之后重新部署

**Comment by lNeverl** [comment]
好的，非常感谢您的解惑，  搜索功能现在正常了，search.xml文件是在public文件夹吗。
