### ISSUE TITLE
你好，我想问一下如何让文章归类到指定page？

### ISSUE THREAD

**Issue by shyanguan** [Shen-Yu/hexo-theme-ayer#28]
感谢分享，很棒的主题！ 我不熟悉hexo操作，搜了半天没弄明白该怎么把文章归类到每个page。
比如说，我有一个page是笔记，我会发表一些笔记在这个page，怎么样才能做到呢？ 我现在只有在`归档`和`主页`能看到发表的文章

**Comment by Shen-Yu** [comment]
@shyanguan 
你好，你说的page就是markdown文章，你可以自行在里面配置文章链接

**Comment by shyanguan** [comment]
了解，谢谢！
