### ISSUE TITLE
markdown语法支持有问题

### ISSUE THREAD

**Issue by JadenNeal** [Shen-Yu/hexo-theme-ayer#3]
比如下面这几句。
1. xxxx
    - xxxx
    - xxxx
2. xxxx
中间的不缩进，而是和1，2这些序号对齐了。但是在github和vs code自带预览上就不会有这些问题。

另外，单行代码的样式可以改进一下吗？现在的样式不突出，和文本没啥区别。

**Comment by Shen-Yu** [comment]
> 比如下面这几句。
> 
> 1. xxxx
>    
>    * xxxx
>    * xxxx
> 2. xxxx
>    中间的不缩进，而是和1，2这些序号对齐了。但是在github和vs code自带预览上就不会有这些问题。
> 
> 另外，单行代码的样式可以改进一下吗？现在的样式不突出，和文本没啥区别。

感谢提出的markdown列表样式问题，已经修复，代码样式也已经改进，请用git pull更新一下
