### ISSUE TITLE
请问大佬相册不能显示缩略图的问题

### ISSUE THREAD

**Issue by heroamd** [Shen-Yu/hexo-theme-ayer#30]
在相册中添加图片后（已经添加文件头）`---
title: 拾影长廊

albums: [
		["img/1.jpg","15435"],
		["img/2.jpg","1543543"],
		["img/2020-3-13-1.jpg","1543534"]	
	
		]
---
`
在本地预览显示的为灰色白块（没有缩略图），点击后可以看到图片
上传至服务器后该页面为空白页面。
请问大佬这个问题怎么办？

**Comment by KernelErr** [comment]
main.css 里面感觉错误地设置了opacity，而且点击图片查看详情的时候会显示fancybox，关闭之后显示photoswipe，有两层大图显示。

**Comment by KernelErr** [comment]
有个临时解决方案，在config里面关闭fancyfox，然后修改main.css中`.justified-gallery>a, .justified-gallery>div, .justified-gallery>figure `和`.justified-gallery>a>a>img, .justified-gallery>a>a>svg, .justified-gallery>a>img, .justified-gallery>a>svg, .justified-gallery>div>a>img, .justified-gallery>div>a>svg, .justified-gallery>div>img, .justified-gallery>div>svg, .justified-gallery>figure>a>img, .justified-gallery>figure>a>svg, .justified-gallery>figure>img, .justified-gallery>figure>svg`的opacity为1。这样照样可以实现以前的效果，不过还是坐等更新。

**Comment by heroamd** [comment]
没学这么看不太懂深哈哈，谢谢你~我坐等更新
