### ISSUE TITLE
Fancybox 和 Photoswipe 存在冲突问题

### ISSUE THREAD

**Issue by KernelErr** [Shen-Yu/hexo-theme-ayer#31]
检查了一下关闭了的 #30 ，在after-footer.ejs里面有一段：
```JavaScript
<% if (theme.image_viewer){ %>
<%- partial('viewer') %>
<% } %>
```
会使用Photoswipe，但是同时又会使用Fancyfox来实现相册效果，所以会有两层大图显示。而且main.css里面fancybox的opacity设置存在错误，导致缩略图无法显示，只有灰色背景。

**Comment by KernelErr** [comment]
可以加一个判断条件is_post()，保证仅仅在文章里面使用Photoswipe，但是修改为了实现缩略图的显示，直接修改main.css，不知道是不是个好方案。

**Comment by Shen-Yu** [comment]
@KernelErr 感谢提出的bug，已经修复~

**Comment by KernelErr** [comment]
修复了之后还是有点问题呀，看起来不能直接删掉Fancybox，移除
```
<% if (theme.image_viewer && is_post()){ %>
<%- partial('viewer') %>
<% } %>
```
看看？

**Comment by KernelErr** [comment]
Photoswipe和Fancybox保留Fancybox，保证文章和page都用Fancybox吧

**Comment by Shen-Yu** [comment]
@KernelErr 谢谢，fancybox太大了， 压缩后的js文件就有70多k，css也有10k，而且只是作为相册放大展示的功能，我个人觉得没有必要，相对而言Photoswipe体积更小，两者功能都相似的，所以我把fancybox都删掉了，现在文章和page都使用fancybox了。

**Comment by KernelErr** [comment]
嗯嗯，非常感谢～
