### ISSUE TITLE
Cannot read property 'offsetTop' of null

### ISSUE THREAD

**Issue by leeuoo11** [Shen-Yu/hexo-theme-ayer#35]
本地搭建时出现了与网站同样的Console error
问题复现网址: https://shen-yu.gitee.io/2019/about/
问题描述: 
             控制台报错: tocbot.min.js:1 Uncaught TypeError: Cannot read property 'offsetTop' of null
浏览器: Google Chrome 
             版本 80.0.3987.149（正式版本） （64 位）

错误log详情:
tocbot.min.js:1 Uncaught TypeError: Cannot read property 'offsetTop' of null
    at r (tocbot.min.js:1)
    at Object.s [as updateToc] (tocbot.min.js:1)
    at Object.<anonymous> (tocbot.min.js:1)
    at Object._scrollListener (tocbot.min.js:1)
    at Object.c.init (tocbot.min.js:1)
    at (index):417

**Comment by Shen-Yu** [comment]
@leeuoo11 这是tocbot.js里面的报错，也就是当页面不存在标题时才会报这个，可以忽略。目前我还没找到解决方法来防止它出现，如果你有好的解决方法，欢迎给我提PR。

**Comment by Shen-Yu** [comment]
@leeuoo11 对了，你可以在文章头部设置`no_toc:true`来防止报错，我已经加了这个，请更新一下主题。

**Comment by leeuoo11** [comment]
> @leeuoo11 对了，你可以在文章头部设置`no_toc:true`来防止报错，我已经加了这个，请更新一下主题。

抱歉，对前端了解不深！
另外，按照你的方法是可行的，nice!
