### ISSUE TITLE
手机访问页面时增加关闭目录的功能

### ISSUE THREAD

**Issue by wangwei1237** [Shen-Yu/hexo-theme-ayer#38]
试用了最新的版本，发现手机上访问时修复了目录不展现的问题，但是如果文章的目录比较长时，在浏览文章时，目录就会遮挡文章了。能否pc和手机做个区分，增加手机上可以不展现目录的功能。

**Comment by Shen-Yu** [comment]
@wangwei1237 感谢提出的bug，确实没有注意到手机端这个问题，现在已经修复~
