### ISSUE TITLE
分类categories bug：同一个分类被分成两个标签

### ISSUE THREAD

**Issue by Zingphoy** [Shen-Yu/hexo-theme-ayer#39]
都是【测试】类别，但是会被归为不同的标签，如下图：
![image](https://user-images.githubusercontent.com/13723733/78579068-fc1b5800-7862-11ea-9a1c-2f21aa90347a.png)
---

一篇文章同时给了多个categories分类，如下两图，前者是【测试】categories放在首位，后者是【测试】categories放在末尾，categories顺序导致了同时出现两个【测试】标签：
![image](https://user-images.githubusercontent.com/13723733/78579150-10f7eb80-7863-11ea-8db1-e5fabf7e7e34.png)
---

![image](https://user-images.githubusercontent.com/13723733/78579268-443a7a80-7863-11ea-86c7-33145f735ef6.png)

**Comment by Shen-Yu** [comment]
一个文章只能对应一个分类，一个文章可以设置多个标签。如果要设置多个类目，建议用标签
