### ISSUE TITLE
categories 无法显示

### ISSUE THREAD

**Issue by Qnurye** [Shen-Yu/hexo-theme-ayer#41]
我按照Ayer的说明已经安装好了，可是 categories 以及 tags 无法正常显示

配置如下：
![configure](https://pic.downk.cc/item/5e8dbf29504f4bcb0444fb91.png)

载入页面如下：
![page](https://pic.downk.cc/item/5e8dbf00504f4bcb0444d65e.png)

有大佬可以给我解答一下吗？谢谢啦～

**Comment by Shen-Yu** [comment]
@Qnurye 这是因为你没有文章设置了分类和标签啊。。

**Comment by Qnurye** [comment]
> @Qnurye 这是因为你没有文章设置了分类和标签啊。。

.....啊啊啊啊我好蠢，谢谢大佬
