### ISSUE TITLE
关于黑夜模式

### ISSUE THREAD

**Issue by ZhengHaoYun** [Shen-Yu/hexo-theme-ayer#43]
您好，启用黑夜模式后，Valine评论区仍然是白色的，非常刺眼，请问是否有办法解决呢？
![image](https://user-images.githubusercontent.com/40732348/79302512-2f26b100-7f1f-11ea-8d48-5e013819e601.png)

**Comment by Shen-Yu** [comment]
@ZhengHaoYun 已经修改了~

**Comment by ZhengHaoYun** [comment]
谢谢！已了解！顺便问下我在页面中增加了一个（本文阅读量），但是我不知道有些什么图标可以放在这个字的前面，请问这些图标是从哪里来的呢？就字数统计和阅读市场前面的那个icon。
![image](https://user-images.githubusercontent.com/40732348/79710496-bbf2b580-82f7-11ea-860c-119aabf2ea5b.png)

**Comment by ZhengHaoYun** [comment]
在main.css里面找到了icon的样式，但是不清楚图标是长什么样的，随便选了一个也还可以了。再次感谢！
![image](https://user-images.githubusercontent.com/40732348/79710745-800c2000-82f8-11ea-9258-3368332183bc.png)
