### ISSUE TITLE
添加# toC

### ISSUE THREAD

**Issue by CYL-home** [Shen-Yu/hexo-theme-ayer#44]
文章目录
用Tocbot解析文章标题并生成目录

将以下配置复制到你ayer目录下的 _config.yml 里：

# Toc
 toc: true

添加这个代码http://localhost:4000/就显示不出来 
是不是因为跟原来主题里存在的这个代码重复的原因

# 文章页是否显示目录
toc: true

**Comment by Shen-Yu** [comment]
@CYL-home 配置重复就会报错！
