### ISSUE TITLE
字体大小修改

### ISSUE THREAD

**Issue by JavanShen** [Shen-Yu/hexo-theme-ayer#45]
标题的减小幅度太大,四级标题就已经比普通文字小了,请问我在哪里可以修改呢

**Comment by Shen-Yu** [comment]
@JavanShen 已经修改，请更新一下

**Comment by JavanShen** [comment]
> @JavanShen 已经修改，请更新一下
好了,感谢

**Comment by IVVIMU** [comment]
请问作者，主页标题字号在那个文件里修改
