### ISSUE TITLE
有关表格居中问题

### ISSUE THREAD

**Issue by AWeng0526** [Shen-Yu/hexo-theme-ayer#46]
今天用md设置表格内容居中发现表格第二列设置居中失败(其他列均成功),排查后发现 ayer/source/dist/main.css中有这么一段:

`
.article-entry table td:nth-child(2) {
    text-align: left !important
}
`
个人将其注释掉了,表格也恢复居中了.不知道是否会引发bug

**Comment by Shen-Yu** [comment]
@AWeng0526 不会
