### ISSUE TITLE
分享按钮点击后不显示图片

### ISSUE THREAD

**Issue by forxhunter** [Shen-Yu/hexo-theme-ayer#47]
![截屏2020-04-30 下午10 27 57](https://user-images.githubusercontent.com/41635675/80722343-da478500-8b31-11ea-9998-2786a9bf2f2c.png)

**Comment by forxhunter** [comment]
这个问题请问是怎么回事呢？我没有修改过源代码

**Comment by Shen-Yu** [comment]
你不是已经显示了吗现在
