### ISSUE TITLE
您好，我能否在您的主题基础上进行修改并发布

### ISSUE THREAD

**Issue by DirtyWorld-png** [Shen-Yu/hexo-theme-ayer#49]
Ayer的作者，您好，请问我是否可以在您的主题Ayer的基础上进行二次修改并在GitHub发布，我会在作品中著名您（Shen-Yu）和“本主题改编自hexo-theme-ayer”，请问可以吗？谢谢

**Comment by Shen-Yu** [comment]
@DirtyWorld-png 可以的，注明链接即可。

**Comment by DirtyWorld-png** [comment]
谢谢！

**Comment by eMUQI** [comment]
https://github.com/Shen-Yu/hexo-theme-ayer/blob/master/LICENSE
