### ISSUE TITLE
无序列表没有吗？

### ISSUE THREAD

**Issue by QQ794763733** [Shen-Yu/hexo-theme-ayer#5]
你好，我在Markdown中使用了-、+、*尝试无序列表但是并没有起效。

我后来检阅了某些文章 发现部分失效 如果直接写的话就看不到前面无序列表的符号

加在引用中能看到 不过非常的窄，也许是文章宽度挡住了CSS的样式。

**Comment by Shen-Yu** [comment]
> 你好，我在Markdown中使用了-、+、*尝试无序列表但是并没有起效。
> 
> 我后来检阅了某些文章 发现部分失效 如果直接写的话就看不到前面无序列表的符号
> 
> 加在引用中能看到 不过非常的窄，也许是文章宽度挡住了CSS的样式。

感谢提出的样式问题，已经修复，请使用git pull更新一下。
