### ISSUE TITLE
归档和首页每一页的数量是否可以添加设置支持

### ISSUE THREAD

**Issue by kycool** [Shen-Yu/hexo-theme-ayer#51]
如题，归档和首页是否可以设置每一页显示的数量，我看归档每一页显示的只有 10 条，下面的空间有点浪费，谢谢 @Shen-Yu

**Comment by Shen-Yu** [comment]
@kycool 你好，请在Hexo的配置文件中修改，[参考文档](https://hexo.io/zh-cn/docs/configuration#%E5%88%86%E9%A1%B5)
