### ISSUE TITLE
请问网易云播放器无法播放的问题

### ISSUE THREAD

**Issue by Plalyy** [Shen-Yu/hexo-theme-ayer#54]
设置为自动播放，且换了不同免费音乐的ID，博客中音乐播放器一直显示是暂停播放状态，点击后无法播放，能请教下解决方法吗

**Comment by jee3** [comment]
我也是 无法播放

**Comment by Shen-Yu** [comment]
这个好像跟网易云音乐那边有关

**Comment by Shen-Yu** [comment]
你可以试试[aplayer](https://github.com/MoePlayer/hexo-tag-aplayer/blob/master/docs/README-zh_cn.md)
