### ISSUE TITLE
代码复制功能异常

### ISSUE THREAD

**Issue by MOOnLyer** [Shen-Yu/hexo-theme-ayer#68]
关闭代码hexo自带的代码高亮之后 代码复制功能出现问题 会到页面右上角 并且只会出现一个，其复制的是最有一个的code block

**Comment by Shen-Yu** [comment]
@MOOnLyer ？截图看看

**Comment by Shen-Yu** [comment]
自带的才会支持

**Comment by MOOnLyer** [comment]
> 自带的才会支持

还需要截图吗 是开启了 自带的highlight 才可以使用代码复制吗？

另外， 我后来加了hightlight.js 但是代码块背景颜色 不会更改 想问下 怎么修改随着style.css 改变代码框的背景色呢

**Comment by Shen-Yu** [comment]
@MOOnLyer 是的，highlight这个不支持呢，直接用markdown的语法就行了
格式是
```
```+语言名（比如java）
//代码内容 ```
```

**Comment by MOOnLyer** [comment]
那怎么修改代码框的背景色呢 现在即使style.css 改变 代码框的背景色也不会变
