### ISSUE TITLE
能否增加公安备案信息尾部显示

### ISSUE THREAD

**Issue by acooler15** [Shen-Yu/hexo-theme-ayer#70]
能不能增加一个公安备案信息显示，可以与ICP备案信息同行

**Comment by Shen-Yu** [comment]
公安备案就是ICP备案啊，配置文件里面已经有了。。

**Comment by Shen-Yu** [comment]
@acooler15

**Comment by acooler15** [comment]
> 公安备案就是ICP备案啊，配置文件里面已经有了。。

[公安联网备案](http://www.beian.gov.cn/portal/index.do)和[ICP备案](http://beian.miit.gov.cn)不同，有的地区强制要求公安联网备案

**Comment by Shen-Yu** [comment]
@acooler15 。。这个，你可以自己加一下，在/layout/_partial/footer.ejs文件里。
