### ISSUE TITLE
一点小建议：给手机端也加上目录

### ISSUE THREAD

**Issue by WTAufPzIv** [Shen-Yu/hexo-theme-ayer#74]
一点小建议：给手机端也加上目录。不然手机端阅读长文体验有点不太好

**Comment by Shen-Yu** [comment]
@WTAufPzIv 谢谢建议，但个人感觉，如果是目录较多，那手机端不是直接占全屏吗

**Comment by WTAufPzIv** [comment]
可以弄个伸缩菜单啥的，点击展开的那种
