### ISSUE TITLE
str.includes is not a function

### ISSUE THREAD

**Issue by wwdok** [Shen-Yu/hexo-theme-ayer#78]
![image](https://user-images.githubusercontent.com/43233772/90306880-e0584a80-df03-11ea-9b2e-71f000bfedbd.png)

**Comment by Shen-Yu** [comment]
@wwdok 你好，请问你装了哪些插件，你本地的hexo版本号是多少，把复现步骤描述详细。

**Comment by wwdok** [comment]
作者你好，应该不是插件的问题，因为我基本没有特意去装很多插件，之前也一直没有遇到过这个，今天遇到这个问题可能是因为我今天尝试同时将我的博客部署到github和gitee上，也就是多了下图中的红圈那一行：
![image](https://user-images.githubusercontent.com/43233772/90309424-266cd880-df1b-11ea-99e8-ba730951e025.png)
我的hexo版本信息如下：
![image](https://user-images.githubusercontent.com/43233772/90309462-6af87400-df1b-11ea-8c50-a5809b0bd173.png)
但是有点奇怪的是，我把新加的那个gitee repo地址注释掉，变成跟原来一样只有github repo，执行`hexo g -d`后照样出现这个报错

**Comment by Shen-Yu** [comment]
@wwdok 新建一个博客目录呢，从0开始看看，逐步排查从哪一步开始报错，如果还不行，加我qq：448766534

**Comment by Shen-Yu** [comment]
我本地的hexo版本是5.0了已经

**Comment by wwdok** [comment]
我把hexo升级到5.0.2后确实没这个报错了。。。
顺便问一下作者，为什么我在markdown里写了这句话“将`opencv\build\x64\vc15\bin`加入用户或者系统的环境变量path里面”，部署后查看网页渲染效果却是“将opencv6415”，被吞掉了好几个字符
![dEURqs.png](https://s1.ax1x.com/2020/08/16/dEURqs.png)
![image](https://user-images.githubusercontent.com/43233772/90328743-6098b180-dfd1-11ea-9146-ebf6e571f7ff.png)
