### ISSUE TITLE
头ejs样式文件内部CDN引用文件错误

### ISSUE THREAD

**Issue by bilikxjh** [Shen-Yu/hexo-theme-ayer#80]
在\layout\_partial\head.ejs中，发现有两处CDN引用文件错误。请作者订正。
![1](https://cdn.jsdelivr.net/gh/bilikxjh/img/bug.png)

**Comment by Shen-Yu** [comment]
@bilikxjh 你好，感谢你的反馈，后缀是会自动补全的，可以看看你本地报错信息吗，我这边是好的呢。

**Comment by bilikxjh** [comment]
尴尬，原来是hexo出问题了，重新安装一下hexo就没报错了。。。抱歉打扰了到您了。
