### ISSUE TITLE
自己建的页面和归档、分类、标签、友链等页面的布局不统一

### ISSUE THREAD

**Issue by bianyukun1213** [Shen-Yu/hexo-theme-ayer#84]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/Shen-Yu/hexo-theme-ayer) version of hexo-theme-ayer.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [Ayer Issues](https://github.com/Shen-Yu/hexo-theme-ayer/issues), which does not help me.

---

## Actual behavior 

- Links to demo site with this feature: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 

1. N/A
2. N/A
3. N/A

## Other Information 

自己建的页面目前用的还是文章的布局，和主题预设页面的布局不同。自建页面的标题不像预设页面的标题是左对齐的，而且自建页面相比于预设页面还多了版权声明、分享等内容。  

可否统一一下自建页面和预设页面的布局？

**Comment by Shen-Yu** [comment]
@bianyukun1213 自建页面是什么意思，new page还是new post，如果是post就是文章的样式呢，如果是page的话就没办法统一，因为不清楚你自己会建什么页面，主题内预设的page才统一左对齐标题

**Comment by bianyukun1213** [comment]
我仿照预设页面的布局改了一个新的布局，标题也是左对齐的，也没有评论等功能。这样在侧边栏切换页面时，感觉就更连贯了。#85

**Comment by Shen-Yu** [comment]
@bianyukun1213 好的，感谢你的改进~
