### ISSUE TITLE
请问本地预览时首页的滚动字幕是可以实现的，但是部署到服务器后就没有效果了，这个改咋解决？

### ISSUE THREAD

**Issue by TURBOyan** [Shen-Yu/hexo-theme-ayer#86]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [ ] I am using [the latest](https://github.com/Shen-Yu/hexo-theme-ayer) version of hexo-theme-ayer.
- [ ] I have reviewed the latest Roadmap on GitHub and searched for current [Ayer Issues](https://github.com/Shen-Yu/hexo-theme-ayer/issues), which does not help me.

---

## Actual behavior 

- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 

1. N/A
2. N/A
3. N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### HTML Configuration

```

```

### Ayer Configuration

```

```

**Comment by Shen-Yu** [comment]
@TURBOyan 你好，请按照模板把环境以及版本号填写完整，这将有助于排查你的问题。
