### ISSUE TITLE
主题页面左侧标签“关于我”的bug

### ISSUE THREAD

**Issue by TURBOyan** [Shen-Yu/hexo-theme-ayer#88]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [ ] I am using [the latest](https://github.com/Shen-Yu/hexo-theme-ayer) version of hexo-theme-ayer.
- [ ] I have reviewed the latest Roadmap on GitHub and searched for current [Ayer Issues](https://github.com/Shen-Yu/hexo-theme-ayer/issues), which does not help me.

---

## Expected behavior 
鼠标停留在“关于我”标签时，应当处于整个“关于我”矩形范围内都可显示选中状态
## Actual behavior 
实际只有当鼠标停留在“关于我”上半部分时，才会触发选中状态，停留在下半部分时，无法触发选中状态

- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 

1. N/A
2. N/A
3. N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### HTML Configuration

```

```

### MiniValine Configuration

```

```

**Comment by Shen-Yu** [comment]
@TURBOyan 你好，你这个bug无法复现呢，可否截图看一下

**Comment by TURBOyan** [comment]
![IMG_3656](https://user-images.githubusercontent.com/57029044/94112195-aae63b80-fe77-11ea-86d1-4d3a3ab5f56c.JPG)

鼠标放在下半部分的时候无法点击
![IMG_3658](https://user-images.githubusercontent.com/57029044/94112277-c6514680-fe77-11ea-82df-aca6574b88b3.JPG)
放在上半部分时可以点击

![IMG_3661](https://user-images.githubusercontent.com/57029044/94112321-d832e980-fe77-11ea-8e34-60608c91b3da.JPG)
其他标签则正常，在方框范围内都可点击

**Comment by TURBOyan** [comment]
[BUG1](http://pic.turbofactory.xyz/BUG1.JPG)
在标签下半部分无法点击
[BUG2](http://pic.turbofactory.xyz/BUG2.JPG)
上半部分可以点击

其他标签则正常，方框范围内都可以点击
[BUG3](http://pic.turbofactory.xyz/BUG3.JPG)

**Comment by Shen-Yu** [comment]
@TURBOyan 这是因为你这笔记本分辨率太低了吧，导致侧边栏放不下。。现在主流分辨率都是1080了
