### ISSUE TITLE
希望新增标题目录能改成全部标题显示的格式

### ISSUE THREAD

**Issue by linzworld** [Shen-Yu/hexo-theme-ayer#89]
目前文章的目录格式，只显示了大标题的内容，然后定位到了对应的大标题下的内容，其下的小标题才会显示出来。
希望能改成全部标题显示的格式
下图是原先的文章目录格式：
![image](https://user-images.githubusercontent.com/48641482/94009111-96059b80-fdd6-11ea-824f-ead046f957e2.png)
下图是到了文章大标题下的内容时显示的目录结构：
![image](https://user-images.githubusercontent.com/48641482/94009454-10362000-fdd7-11ea-97db-9e55ddb233df.png)
而希望修改成的目录格式为
![image](https://user-images.githubusercontent.com/48641482/94008900-47f09800-fdd6-11ea-8541-63beb1695b7b.png)
 类似于这个样子，或者是否已经有了这个格式的设置，如果有，麻烦回答下，非常感谢

**Comment by Shen-Yu** [comment]
@linzworld 你好，这个本来就是这样随着滚动而展开的，如果一下子显示全部的话，太长了就会撑开页面，导致样式问题。

**Comment by linzworld** [comment]
好的，谢谢您
