### ISSUE TITLE
请问大佬如何解决文章图片显示问题？

### ISSUE THREAD

**Issue by guhailong18** [Shen-Yu/hexo-theme-ayer#9]
非常抱歉这个问题似乎与你的主题是无关的，但是我真的很想知道你是如何使你文章的图片可以正常显示的，并且百度上的，我所能找到的方法都无法解决我的问题，我是使用Typora进行编写的

**Comment by charlieJ107** [comment]
https://hexo.io/zh-cn/docs/asset-folders.html 你可以在这里找到有关资源文件夹的介绍, 如果你的图片很多, 很可能会造成仓库体积过大, 一方面可能会被限制上传, 另一方面也会导致读取变慢. 可以考虑通过第三方图床来解决.
