### ISSUE TITLE
QQ分享和推特分享出错

### ISSUE THREAD

**Issue by Sh1-5** [Shen-Yu/hexo-theme-ayer#92]
1.qq分享时登录qq账号，长时间登不上，登上去之后，显示分享成功，实际上并没有给好友，群，空间发送链接。

2.推特分享跳到空白页面无反应。

**Comment by Shen-Yu** [comment]
qq和推特的分享api链接错误，暂时只能等官方修复分享链接

**Comment by DF-Master** [comment]
目前微信的分享功能也无效，能否给出一个解决方案？

**Comment by Shen-Yu** [comment]
抱歉，之前的qq和推特分享功能确实是代码存在bug，已经在最新版本(1.8.14)中进行了修复，感谢反馈！请让这个issue保持open，以帮助其他遇到相同问题的朋友们。

**Comment by DF-Master** [comment]
谢谢！更新了layout文件夹与package.json之后qq可行，但微信仍然无法分享。

**Comment by Shen-Yu** [comment]
@DF-Master 微信分享应该不存在问题吧，请参考 [我的博客](https://shen-yu.gitee.io/)

**Comment by DF-Master** [comment]
![Screenshot_20210311_163714_com.microsoft.emmx.jpg](https://user-images.githubusercontent.com/69508342/110759153-43d30c80-8288-11eb-8aec-b2253631be7d.jpg)我这好像不行哎

**Comment by Shen-Yu** [comment]
。。这个要用微信扫啊

**Comment by DF-Master** [comment]
明白了！谢谢作者的耐心解答~
