### ISSUE TITLE
友情链接替换

### ISSUE THREAD

**Issue by Restent** [Shen-Yu/hexo-theme-ayer#94]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/Shen-Yu/hexo-theme-ayer) version of hexo-theme-ayer.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [Ayer Issues](https://github.com/Shen-Yu/hexo-theme-ayer/issues), which does not help me.
---
沈宇大大您好
我想使用一个独立的 friends 来展现我的朋友们的站点，可是无论我怎么修改，它只会显示您新版设置的“友情链接”的内容
请问该如何修改？谢谢。
---

## Other Information 
Browser: Microsoft Edge
System: Windows 10 Pro (x64,1909)

**Comment by Shen-Yu** [comment]
如果你用了friends模板，那会用主题默认的样式，你可以新建个其他名字的页面
