### ISSUE TITLE
表格怎么靠左

### ISSUE THREAD

**Issue by pxim** [Shen-Yu/hexo-theme-ayer#95]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [ ] I am using [the latest](https://github.com/Shen-Yu/hexo-theme-ayer) version of hexo-theme-ayer.
- [ ] I have reviewed the latest Roadmap on GitHub and searched for current [Ayer Issues](https://github.com/Shen-Yu/hexo-theme-ayer/issues), which does not help me.

我现在用html语法，图片可以靠左，表格用的md语法，在Typora编辑器中，表格是靠左的，但是渲染成网页后，不靠左
网页：
![image](https://user-images.githubusercontent.com/5111701/98498811-cc15b680-2282-11eb-90dd-6c2c53324872.png)
https://pxim.github.io/2020/11/09/DResDevKit/course-mobile/

Typora：
![image](https://user-images.githubusercontent.com/5111701/98502727-b063dd80-228d-11eb-9b10-337073e5c5df.png)

![image](https://user-images.githubusercontent.com/5111701/98502477-0e43f580-228d-11eb-8d06-0e3c1883cb04.png)

---

**Comment by pxim** [comment]
![image](https://user-images.githubusercontent.com/5111701/98506297-22d8bb80-2296-11eb-9552-eb77df6cde36.png)
添加了这句，暂时可以靠左了

**Comment by Shen-Yu** [comment]
样式差异，请自行调整
