### ISSUE TITLE
建议适配twikoo评论系统

### ISSUE THREAD

**Issue by xingshu1990** [Shen-Yu/hexo-theme-ayer#98]
ayer本身适配了Valine 等几个评论系统，但是LeanCloud中文版没有提供二级域名，
中文版 外文版的免费版还需要折腾定时任务，
邮件推送又要第三方，对小白不友好。
原先已经在https://github.com/imaegoo/twikoo
的Issue发起了申请，不过可能作者忙着做其他功能，所以就暂时没看到进度信息。
后考虑今后可能要平滑升级主题，所以还是过来建议主题作者适配这个评论系统，谢谢。

**Comment by Shen-Yu** [comment]
已经添加。106f2494eb9d7cbe691bf8c998aee73feb5484e2

**Comment by xingshu1990** [comment]
谢谢 这就使用

**Comment by xingshu1990** [comment]
> 已经添加[。2dd7a54](https://github.com/Shen-Yu/hexo-theme-ayer/commit/2dd7a5408b9059f54772bcd154af65d3e2d48f0c)

按照教程中的说法，复制_config.yml 删除主题文件，重新安装主题，重新覆盖_config.yml然后网站还是没显示评论系统，已经改过_config.yml中的ID
网站是https://xingshu1990.github.io/

**Comment by Shen-Yu** [comment]
@xingshu1990 你好，我本地测试是可以的呢，如下图：
![QQ截图20201224174222.png](https://i.loli.net/2020/12/24/N6Xa5Th7pd9G8By.png)
